# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-19 23:12
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import taggit.managers


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('taggit', '0002_auto_20150616_2121'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(max_length=255, unique=True)),
                ('published_date', models.DateTimeField(blank=True, null=True, verbose_name='published on')),
                ('creation_date', models.DateTimeField(auto_now=True, verbose_name='date created')),
                ('last_update', models.DateTimeField(auto_now=True, verbose_name='updated')),
                ('body', models.TextField()),
                ('title', models.CharField(max_length=255)),
                ('summary', models.TextField(blank=True)),
                ('state', models.CharField(choices=[('draft', 'Draft'), ('masked', 'Masked'), ('published', 'Published')], default='draft', max_length=32)),
                ('allow_comments', models.BooleanField(default=False)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'article',
                'verbose_name_plural': 'articles',
                'ordering': ['-published_date', '-last_update'],
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=255)),
                ('slug', models.SlugField(max_length=255, unique=True)),
            ],
            options={
                'verbose_name': 'category',
                'verbose_name_plural': 'categories',
                'ordering': ['label'],
            },
        ),
        migrations.CreateModel(
            name='Menu',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=64)),
                ('url', models.CharField(max_length=254)),
                ('sequence', models.IntegerField()),
                ('visible', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'index menu',
                'verbose_name_plural': 'index menus',
                'ordering': ('sequence',),
            },
        ),
        migrations.AddField(
            model_name='article',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='wbo.Category'),
        ),
        migrations.AddField(
            model_name='article',
            name='tags',
            field=taggit.managers.TaggableManager(help_text='A comma-separated list of tags.', through='taggit.TaggedItem', to='taggit.Tag', verbose_name='Tags'),
        ),
    ]
